# General
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kentarosasaki/vim-emacs-bindings'

[[plugins]]
repo = 'moll/vim-bbye'
build = 'make'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
