# General
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_source = 'deoplete-go'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'tpope/vim-abolish'

# Golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

# React
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'
hook_source = '''
    let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
hook_source = '''
    let g:jsx_ext_required = 0
'''

# Protobuf
[[plugins]]
repo = 'uarun/vim-protobuf'

# C++
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'

# Plantuml
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['pu', 'uml', 'plantuml']
