# General
[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'tpope/vim-abolish'

# Golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

# Protobuf
[[plugins]]
repo = 'uarun/vim-protobuf'

# C++
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'

# Plantuml
[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['pu', 'uml', 'plantuml']
